/**
 * src/setup/setupRoutes.ts — First-run wizard API.
 *
 * Endpoints (all unauthenticated — the wizard only runs before DATABASE_URL is
 * set, and detectSetup() locks it once a host is configured):
 *   POST /api/setup/test-db   — validate a Postgres connection string
 *   POST /api/setup/finalize  — write .env (with freshly generated secrets +
 *                               the AES-256-GCM data key), run migrations, seed
 *                               built-in roles + the first admin, then signal
 *                               the operator to restart into the full app.
 *
 * SECURITY: the generated CHARON_DATA_KEY is what encrypts every at-rest secret.
 * It is written to .env (mode 0600) and must be backed up to Key Vault — losing
 * it makes stored integration credentials unrecoverable.
 */

import { Router } from "express";
import { z } from "zod";
import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync, chmodSync } from "node:fs";
import pg from "pg";
import { ENV_FILE } from "../utils/paths.js";
import { markSetupComplete } from "./detectSetup.js";
import { AppError } from "../utils/errors.js";
import { logger } from "../utils/logger.js";

const router = Router();

const dbSchema = z.object({ databaseUrl: z.string().min(1) });

async function testConnection(databaseUrl: string): Promise<void> {
  const client = new pg.Client({ connectionString: databaseUrl, connectionTimeoutMillis: 5000 });
  try {
    await client.connect();
    await client.query("SELECT 1");
  } finally {
    await client.end().catch(() => {});
  }
}

router.post("/test-db", async (req, res) => {
  try {
    const { databaseUrl } = dbSchema.parse(req.body);
    await testConnection(databaseUrl);
    res.json({ ok: true });
  } catch (err: any) {
    res.status(400).json({ ok: false, error: err?.message ?? "Connection failed" });
  }
});

const finalizeSchema = z.object({
  databaseUrl: z.string().min(1),
  adminUsername: z.string().min(3).max(64),
  adminPassword: z.string().min(12, "Admin password must be at least 12 characters"),
  publicUrl: z.string().url().optional(),
});

router.post("/finalize", async (req, res, next) => {
  try {
    if (existsSync(ENV_FILE)) {
      throw new AppError(409, ".env already exists — refusing to overwrite. Remove it to re-run setup.");
    }
    const input = finalizeSchema.parse(req.body);
    await testConnection(input.databaseUrl);

    const sessionSecret = randomBytes(48).toString("base64url");
    const healthToken = randomBytes(24).toString("base64url");
    const metricsToken = randomBytes(24).toString("base64url");
    const dataKey = randomBytes(32).toString("base64");

    const envBody = [
      "# Charon configuration — generated by first-run setup.",
      "# SECURITY: this file contains secrets and the at-rest data key.",
      "#   - Never commit it (the repo is public; .gitignore blocks it).",
      "#   - Back up CHARON_DATA_KEY to Key Vault — losing it makes stored",
      "#     integration credentials unrecoverable.",
      "",
      `DATABASE_URL=${input.databaseUrl}`,
      `SESSION_SECRET=${sessionSecret}`,
      `HEALTH_TOKEN=${healthToken}`,
      `METRICS_TOKEN=${metricsToken}`,
      `CHARON_DATA_KEY=${dataKey}`,
      input.publicUrl ? `CHARON_PUBLIC_URL=${input.publicUrl}` : "# CHARON_PUBLIC_URL=https://charon.example.com",
      "NODE_ENV=production",
      "",
    ].join("\n");

    writeFileSync(ENV_FILE, envBody, { encoding: "utf-8" });
    try {
      chmodSync(ENV_FILE, 0o600);
    } catch {
      /* best-effort on non-POSIX */
    }

    const childEnv = {
      ...process.env,
      DATABASE_URL: input.databaseUrl,
      CHARON_DATA_KEY: dataKey,
      CHARON_SEED_ADMIN_USER: input.adminUsername,
      CHARON_SEED_ADMIN_PASSWORD: input.adminPassword,
    };

    // Apply schema, then seed built-in roles + the first admin. execFileSync
    // (not a shell) so operator-supplied values never reach a shell.
    execFileSync("npx", ["prisma", "migrate", "deploy"], { env: childEnv, stdio: "inherit" });
    execFileSync(
      "node",
      ["--import", "tsx/esm", "prisma/seed.ts"],
      { env: childEnv, stdio: "inherit" },
    );

    markSetupComplete();
    logger.info("First-run setup finalized; restart Charon to boot the full app.");
    res.json({ ok: true, message: "Setup complete. Restart Charon to start the application." });
  } catch (err) {
    next(err);
  }
});

export default router;
